# Generated by Django 4.1.2 on 2023-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notesapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(default="title", max_length=150),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(default="title", max_length=150),
        ),
    ]
