# Generated by Django 4.1.2 on 2023-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notesapi", "0003_remove_text_notebook_remove_video_notebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, default="description", null=True),
        ),
    ]
